CREATE POLICY "invites_select_members" ON "invites" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("invites"."workspace_id"));--> statement-breakpoint
CREATE POLICY "invites_insert_roles" ON "invites" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role("invites"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "invites_update_roles" ON "invites" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("invites"."workspace_id") in ('owner', 'agent')) WITH CHECK (public.workspace_role("invites"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "invites_delete_roles" ON "invites" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("invites"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "profiles_select_self_or_comember" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ("profiles"."id" = (select auth.uid()) or public.shares_workspace_with("profiles"."id"));--> statement-breakpoint
CREATE POLICY "profiles_update_self" ON "profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ("profiles"."id" = (select auth.uid())) WITH CHECK ("profiles"."id" = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "workspace_members_select_members" ON "workspace_members" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("workspace_members"."workspace_id"));--> statement-breakpoint
CREATE POLICY "workspace_members_update_owner" ON "workspace_members" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("workspace_members"."workspace_id") in ('owner')) WITH CHECK (public.workspace_role("workspace_members"."workspace_id") in ('owner'));--> statement-breakpoint
CREATE POLICY "workspace_members_delete_owner_or_self" ON "workspace_members" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("workspace_members"."workspace_id") in ('owner') or "workspace_members"."user_id" = (select auth.uid()));--> statement-breakpoint
CREATE POLICY "workspaces_select_members" ON "workspaces" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("workspaces"."id"));--> statement-breakpoint
CREATE POLICY "workspaces_update_owner" ON "workspaces" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("workspaces"."id") = 'owner') WITH CHECK (public.workspace_role("workspaces"."id") = 'owner');--> statement-breakpoint
CREATE POLICY "workspaces_delete_owner" ON "workspaces" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("workspaces"."id") = 'owner');--> statement-breakpoint
CREATE POLICY "contacts_select_members" ON "contacts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("contacts"."workspace_id"));--> statement-breakpoint
CREATE POLICY "contacts_insert_roles" ON "contacts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role("contacts"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "contacts_update_roles" ON "contacts" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("contacts"."workspace_id") in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role("contacts"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "contacts_delete_roles" ON "contacts" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("contacts"."workspace_id") in ('owner', 'agent', 'assistant'));