CREATE POLICY "documents_select_members" ON "documents" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((public.is_workspace_member(public.property_workspace("documents"."property_id")) or (public.is_property_person("documents"."property_id") and coalesce(("documents"."meta"->>'shared')::boolean, false))));--> statement-breakpoint
CREATE POLICY "documents_insert_roles" ON "documents" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("documents"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "documents_update_roles" ON "documents" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("documents"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("documents"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "documents_delete_roles" ON "documents" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("documents"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "inventory_items_select_members" ON "inventory_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((public.is_workspace_member(public.property_workspace("inventory_items"."property_id")) or public.is_property_person("inventory_items"."property_id")));--> statement-breakpoint
CREATE POLICY "inventory_items_insert_roles" ON "inventory_items" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("inventory_items"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "inventory_items_update_roles" ON "inventory_items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("inventory_items"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("inventory_items"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "inventory_items_delete_roles" ON "inventory_items" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("inventory_items"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "properties_select_members_or_people" ON "properties" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((public.is_workspace_member("properties"."workspace_id") or public.is_property_person("properties"."id")));--> statement-breakpoint
CREATE POLICY "properties_insert_roles" ON "properties" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.is_workspace_member("properties"."workspace_id"));--> statement-breakpoint
CREATE POLICY "properties_update_roles" ON "properties" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.is_workspace_member("properties"."workspace_id")) WITH CHECK (public.is_workspace_member("properties"."workspace_id"));--> statement-breakpoint
CREATE POLICY "properties_delete_roles" ON "properties" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("properties"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "property_media_select_members" ON "property_media" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((public.is_workspace_member(public.property_workspace("property_media"."property_id")) or public.is_property_person("property_media"."property_id")));--> statement-breakpoint
CREATE POLICY "property_media_insert_roles" ON "property_media" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("property_media"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "property_media_update_roles" ON "property_media" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("property_media"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("property_media"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "property_media_delete_roles" ON "property_media" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("property_media"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "property_people_select_members" ON "property_people" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((public.is_workspace_member(public.property_workspace("property_people"."property_id")) or public.is_property_person("property_people"."property_id")));--> statement-breakpoint
CREATE POLICY "property_people_insert_roles" ON "property_people" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("property_people"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "property_people_update_roles" ON "property_people" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("property_people"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("property_people"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "property_people_delete_roles" ON "property_people" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("property_people"."property_id")) in ('owner', 'agent', 'assistant'));