ALTER TABLE "applications" ADD CONSTRAINT "applications_property_contact_unique" UNIQUE("property_id","contact_id");--> statement-breakpoint
ALTER TABLE "form_submissions" ADD CONSTRAINT "form_submissions_form_contact_unique" UNIQUE("form_id","contact_id");--> statement-breakpoint
CREATE POLICY "applications_select_members" ON "applications" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member(public.property_workspace("applications"."property_id")));--> statement-breakpoint
CREATE POLICY "applications_insert_roles" ON "applications" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("applications"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "applications_update_roles" ON "applications" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("applications"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("applications"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "applications_delete_roles" ON "applications" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("applications"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "form_submissions_select_members" ON "form_submissions" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member(public.property_workspace((select f.property_id from public.forms f where f.id = "form_submissions"."form_id"))));--> statement-breakpoint
CREATE POLICY "form_submissions_insert_roles" ON "form_submissions" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace((select f.property_id from public.forms f where f.id = "form_submissions"."form_id"))) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "form_submissions_update_roles" ON "form_submissions" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace((select f.property_id from public.forms f where f.id = "form_submissions"."form_id"))) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace((select f.property_id from public.forms f where f.id = "form_submissions"."form_id"))) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "form_submissions_delete_roles" ON "form_submissions" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace((select f.property_id from public.forms f where f.id = "form_submissions"."form_id"))) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "forms_select_members" ON "forms" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member(public.property_workspace("forms"."property_id")));--> statement-breakpoint
CREATE POLICY "forms_insert_roles" ON "forms" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("forms"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "forms_update_roles" ON "forms" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("forms"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("forms"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "forms_delete_roles" ON "forms" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("forms"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "owner_views_select_members" ON "owner_views" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member(public.property_workspace("owner_views"."property_id")));--> statement-breakpoint
CREATE POLICY "owner_views_insert_roles" ON "owner_views" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("owner_views"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "owner_views_update_roles" ON "owner_views" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("owner_views"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("owner_views"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "owner_views_delete_roles" ON "owner_views" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("owner_views"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "pipeline_stages_select_members" ON "pipeline_stages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member(public.property_workspace("pipeline_stages"."property_id")));--> statement-breakpoint
CREATE POLICY "pipeline_stages_insert_roles" ON "pipeline_stages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role(public.property_workspace("pipeline_stages"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "pipeline_stages_update_roles" ON "pipeline_stages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role(public.property_workspace("pipeline_stages"."property_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role(public.property_workspace("pipeline_stages"."property_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "pipeline_stages_delete_roles" ON "pipeline_stages" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role(public.property_workspace("pipeline_stages"."property_id")) in ('owner', 'agent', 'assistant'));