ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_external_unique" UNIQUE("conversation_id","external_id");--> statement-breakpoint
CREATE POLICY "ai_drafts_select_members" ON "ai_drafts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member((select c.workspace_id from public.conversations c where c.id = "ai_drafts"."conversation_id")));--> statement-breakpoint
CREATE POLICY "ai_drafts_insert_roles" ON "ai_drafts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "ai_drafts"."conversation_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_drafts_update_roles" ON "ai_drafts" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "ai_drafts"."conversation_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "ai_drafts"."conversation_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_drafts_delete_roles" ON "ai_drafts" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "ai_drafts"."conversation_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "conversations_select_members" ON "conversations" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("conversations"."workspace_id"));--> statement-breakpoint
CREATE POLICY "conversations_insert_roles" ON "conversations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role("conversations"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "conversations_update_roles" ON "conversations" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("conversations"."workspace_id") in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role("conversations"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "conversations_delete_roles" ON "conversations" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("conversations"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "integrations_select_members" ON "integrations" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("integrations"."workspace_id"));--> statement-breakpoint
CREATE POLICY "integrations_insert_roles" ON "integrations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role("integrations"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "integrations_update_roles" ON "integrations" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("integrations"."workspace_id") in ('owner', 'agent')) WITH CHECK (public.workspace_role("integrations"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "integrations_delete_roles" ON "integrations" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("integrations"."workspace_id") in ('owner', 'agent'));--> statement-breakpoint
CREATE POLICY "messages_select_members" ON "messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member((select c.workspace_id from public.conversations c where c.id = "messages"."conversation_id")));--> statement-breakpoint
CREATE POLICY "messages_insert_roles" ON "messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "messages"."conversation_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "messages_update_roles" ON "messages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "messages"."conversation_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "messages"."conversation_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "messages_delete_roles" ON "messages" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role((select c.workspace_id from public.conversations c where c.id = "messages"."conversation_id")) in ('owner', 'agent', 'assistant'));