ALTER TABLE "profiles" ADD COLUMN "ai_signature" text;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "ai_language" text DEFAULT 'en' NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "ai_tone" text DEFAULT 'friendly' NOT NULL;--> statement-breakpoint
ALTER TABLE "ai_drafts" ADD COLUMN "acceptance_pct" integer;--> statement-breakpoint
CREATE POLICY "ai_messages_select_members" ON "ai_messages" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member((select t.workspace_id from public.ai_threads t where t.id = "ai_messages"."thread_id")));--> statement-breakpoint
CREATE POLICY "ai_messages_insert_roles" ON "ai_messages" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role((select t.workspace_id from public.ai_threads t where t.id = "ai_messages"."thread_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_messages_update_roles" ON "ai_messages" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role((select t.workspace_id from public.ai_threads t where t.id = "ai_messages"."thread_id")) in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role((select t.workspace_id from public.ai_threads t where t.id = "ai_messages"."thread_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_messages_delete_roles" ON "ai_messages" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role((select t.workspace_id from public.ai_threads t where t.id = "ai_messages"."thread_id")) in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_threads_select_members" ON "ai_threads" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("ai_threads"."workspace_id"));--> statement-breakpoint
CREATE POLICY "ai_threads_insert_roles" ON "ai_threads" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role("ai_threads"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_threads_update_roles" ON "ai_threads" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("ai_threads"."workspace_id") in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role("ai_threads"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "ai_threads_delete_roles" ON "ai_threads" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("ai_threads"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "embeddings_select_members" ON "embeddings" AS PERMISSIVE FOR SELECT TO "authenticated" USING (public.is_workspace_member("embeddings"."workspace_id"));--> statement-breakpoint
CREATE POLICY "embeddings_insert_roles" ON "embeddings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (public.workspace_role("embeddings"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "embeddings_update_roles" ON "embeddings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (public.workspace_role("embeddings"."workspace_id") in ('owner', 'agent', 'assistant')) WITH CHECK (public.workspace_role("embeddings"."workspace_id") in ('owner', 'agent', 'assistant'));--> statement-breakpoint
CREATE POLICY "embeddings_delete_roles" ON "embeddings" AS PERMISSIVE FOR DELETE TO "authenticated" USING (public.workspace_role("embeddings"."workspace_id") in ('owner', 'agent', 'assistant'));